 version: '3'
 services:
   apache-php:
     build:
       context: ./..
       dockerfile: ./docker/apache-php/Dockerfile
     image: apache-php
     container_name: apache-php
     expose:
       - "9000"
     ports:
       - 80:80
     volumes:
       - ./../files:/var/www/html
     restart: always
     networks:
       - dnetwork
   mysql:
     build:
       context: .
       dockerfile: ./mysql-db/Dockerfile
     image: mysql-db
     container_name: mysql-db
     environment:
       MYSQL_USER: mysql
       MYSQL_PASSWORD: 1
       MYSQL_ROOT_PASSWORD: 1
     ports:
       - 3306:3306
     volumes:
       - ./mysql-db/databases:/var/lib/mysql
     restart: always
     networks:
     - dnetwork
 networks:
  dnetwork:

